<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ruru</name>
  <uuid>ae9c15ce-8c62-45d5-a0f4-678a24f1b527</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "nothing" ;
print "we're doomed";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
