<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>11.1 - household gross income</name>
  <uuid>10095c7c-d914-43a2-93c8-c496bd047a87</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the value of the R_GRSS_INC_R_AMT of decision is more than 18000
then
	set the value of the R_RL_PROP_CR_AMT of decision to 0;
    add A099 to the codes of the R_GRSS_INC_R_AMT of decision ;
    set the TEMP_ARC of decision to A099 ; 
    set the IT214_COUNTER of the globals of decision to (the IT214_COUNTER of the globals of decision + 1);
    set the TEMP_CR_DENIED_IND of decision to Present; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
