<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>2.1 - determine resident state with IT201</name>
  <uuid>1d2130ea-1ec8-436d-b849-2f0110f21d33</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	IT201 is not null
then 
	set the value of the R_RSDT_IND of decision to Standard ( 1 );
    set the TEMP_FAGI of decision to the value of the FEDAGI_RCOMP_AMT of IT201 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
