<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>4 - household gross income with RPTC</name>
  <uuid>3e0cc7fb-2da2-44f6-a4c1-015e331c2922</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the TEMP_CR_DENIED_IND of decision is Absent
then
	lookup RPTC from 'reference data' for $ the value of the R_GRSS_INC_R_AMT of decision ;
    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
