<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>5.2 - compute temp line 18</name>
  <uuid>b6f83845-9407-4cfc-ad89-5b0438aec289</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the TEMP_CR_DENIED_IND of decision is Present 
    or the value of the R_GRSS_INC_R_AMT of decision is less than 0
then
	set the TEMP_LINE18 of decision to 0;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
