<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>6 - compute temp line 30</name>
  <uuid>f97939dd-bc38-491f-ad00-96004ceacdd9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the  TEMP_CR_DENIED_IND of decision is Absent
then
	set the TEMP_LINE30 of decision 
    	to max (0,(the value of the R_RL_PROP_TX_AMT of decision - the TEMP_LINE18 of decision));
    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
