<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>initialize decision</name>
  <uuid>74433d22-62f9-4d3e-9bbb-b510e8db40c9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'input form' ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
