<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>initialize decision</name>
  <uuid>06f2f0ca-47b9-4d70-adf0-ddbb11254559</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'input form' ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
