<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>initialize decision</name>
  <uuid>90b41027-6804-4598-aab6-2a955440076b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'input form' ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
