<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ruru</name>
  <uuid>cac01fbd-6174-490a-977c-0db8f7e66c75</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "done" ;
print "done" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
