<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>accumulate schedule B table</name>
  <uuid>c17e2011-f4ad-4d75-b6db-e652cc5a8587</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[print "on est un peu dans la merde...]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
